require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ApplicationVersionsController do

  def mock_application_version(stubs={})
    @mock_application_version ||= mock_model(ApplicationVersion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all application_versions as @application_versions" do
      ApplicationVersion.stub(:all) { [mock_application_version] }
      get :index
      assigns(:application_versions).should eq([mock_application_version])
    end
  end

  describe "GET show" do
    it "assigns the requested application_version as @application_version" do
      ApplicationVersion.stub(:find).with("37") { mock_application_version }
      get :show, :id => "37"
      assigns(:application_version).should be(mock_application_version)
    end
  end

  describe "GET new" do
    it "assigns a new application_version as @application_version" do
      ApplicationVersion.stub(:new) { mock_application_version }
      get :new
      assigns(:application_version).should be(mock_application_version)
    end
  end

  describe "GET edit" do
    it "assigns the requested application_version as @application_version" do
      ApplicationVersion.stub(:find).with("37") { mock_application_version }
      get :edit, :id => "37"
      assigns(:application_version).should be(mock_application_version)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created application_version as @application_version" do
        ApplicationVersion.stub(:new).with({'these' => 'params'}) { mock_application_version(:save => true) }
        post :create, :application_version => {'these' => 'params'}
        assigns(:application_version).should be(mock_application_version)
      end

      it "redirects to the created application_version" do
        ApplicationVersion.stub(:new) { mock_application_version(:save => true) }
        post :create, :application_version => {}
        response.should redirect_to(application_version_url(mock_application_version))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved application_version as @application_version" do
        ApplicationVersion.stub(:new).with({'these' => 'params'}) { mock_application_version(:save => false) }
        post :create, :application_version => {'these' => 'params'}
        assigns(:application_version).should be(mock_application_version)
      end

      it "re-renders the 'new' template" do
        ApplicationVersion.stub(:new) { mock_application_version(:save => false) }
        post :create, :application_version => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested application_version" do
        ApplicationVersion.stub(:find).with("37") { mock_application_version }
        mock_application_version.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :application_version => {'these' => 'params'}
      end

      it "assigns the requested application_version as @application_version" do
        ApplicationVersion.stub(:find) { mock_application_version(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:application_version).should be(mock_application_version)
      end

      it "redirects to the application_version" do
        ApplicationVersion.stub(:find) { mock_application_version(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(application_version_url(mock_application_version))
      end
    end

    describe "with invalid params" do
      it "assigns the application_version as @application_version" do
        ApplicationVersion.stub(:find) { mock_application_version(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:application_version).should be(mock_application_version)
      end

      it "re-renders the 'edit' template" do
        ApplicationVersion.stub(:find) { mock_application_version(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested application_version" do
      ApplicationVersion.stub(:find).with("37") { mock_application_version }
      mock_application_version.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the application_versions list" do
      ApplicationVersion.stub(:find) { mock_application_version }
      delete :destroy, :id => "1"
      response.should redirect_to(application_versions_url)
    end
  end

end
